SELECT mo.STARNAME FROM MOVIESTAR ms, STARSIN mo
WHERE ms.GENDER = 'm' AND mo.MOVIETITLE = 'The Usual Suspects' AND ms.NAME = mo.STARNAME;

SELECT STARNAME FROM MOVIE mv ,STARSIN sn
WHERE mv.YEAR='1995' AND mv.STUDIONAME = 'MGM' AND mv.TITLE = sn.MOVIETITLE;

SELECT DISTINCT me.NAME
FROM MOVIEEXEC me, MOVIE mo, STUDIO st
WHERE mo.STUDIONAME ='MGM' 
AND me.CERT# = mo.PRODUCERC# 
AND st.NAME = mo.STUDIONAME;

SELECT o1.TITLE 
FROM MOVIE o1, MOVIE o2
WHERE o2.TITLE='Star Wars' 
AND o1.LENGTH>o2.LENGTH;

SELECT o1.NAME 
FROM MOVIEEXEC o1, MOVIEEXEC o2
WHERE o2.NAME ='Stephen Spielberg' 
AND o1.NETWORTH>o2.NETWORTH;

SELECT o3.TITLE
FROM MOVIEEXEC o1, MOVIEEXEC o2, MOVIE o3
WHERE o2.NAME ='Stephen Spielberg' 
AND o1.NETWORTH>o2.NETWORTH
AND o1.CERT# = o3.PRODUCERC#;

