SELECT S1.NAME FROM SHIPS S1,CLASSES CL
WHERE CL.CLASS = S1.CLASS 
AND DISPLACEMENT > 50000;

SELECT Distinct s.NAME, DISPLACEMENT, NUMGUNS FROM CLASSES c, SHIPS s, BATTLES b,OUTCOMES o
WHERE b.NAME ='Guadalcanal' 
AND b.NAME = o.battle
AND S.NAME = O.SHIP
AND c.CLASS=s.CLASS;

SELECT DISTINCT o1.COUNTRY FROM CLASSES o1, CLASSES o2
WHERE o1.TYPE = 'bb' 
AND o2.TYPE = 'bc' 
AND o1.COUNTRY = o2.COUNTRY;

SELECT o1.SHIP FROM OUTCOMES o1, OUTCOMES o2
WHERE o1.SHIP = o2.SHIP 
AND o1.BATTLE != o2.BATTLE
AND o1.RESULT = 'damaged'
