SELECT ME.NAME,M.TITLE FROM MOVIE M JOIN MOVIEEXEC ME ON M.PRODUCERC#=ME.CERT#
WHERE ME.NAME IN (SELECT ME2.NAME FROM MOVIEEXEC ME2 JOIN MOVIE M2 ON M2.PRODUCERC# = ME2.CERT# WHERE M2.TITLE = 'Star Wars');

SELECT DISTINCT ME.NAME FROM MOVIEEXEC ME JOIN MOVIE M ON ME.CERT#=M.PRODUCERC#
WHERE M.TITLE IN (SELECT M2.TITLE FROM MOVIE M2 JOIN STARSIN SI ON M2.TITLE=SI.MOVIETITLE WHERE SI.STARNAME='Harrison Ford');

SELECT DISTINCT S.NAME,SI.STARNAME 
FROM STUDIO S 
JOIN MOVIE MV ON S.NAME=MV.STUDIONAME
JOIN STARSIN SI ON MV.TITLE=SI.MOVIETITLE;

SELECT SI.STARNAME,NETWORTH,MV.TITLE 
FROM STARSIN SI 
JOIN MOVIE MV ON SI.MOVIETITLE=MV.TITLE
JOIN MOVIEEXEC ME ON MV.PRODUCERC#=ME.CERT#
WHERE ME.NETWORTH>=ALL(SELECT NETWORTH FROM MOVIEEXEC)

SELECT MS.NAME,TITLE
FROM MOVIESTAR MS 
LEFT JOIN STARSIN SI ON SI.STARNAME=MS.NAME
LEFT JOIN MOVIE MV ON MV.TITLE=SI.MOVIETITLE
WHERE MS.NAME NOT IN (SELECT SI2.STARNAME FROM STARSIN SI2 JOIN MOVIE MV ON SI2.MOVIETITLE=MV.TITLE)

