SELECT P.MAKER,P.MODEL,P.TYPE FROM PRODUCT P 
LEFT JOIN LAPTOP L ON P.model=L.model
LEFT JOIN PC P1 ON P1.model = P.model
LEFT JOIN PRINTER PR1 ON PR1.model = P.model
WHERE P.model NOT IN (SELECT MODEL FROM PC)
AND P.model NOT IN (SELECT MODEL FROM PRINTER)
AND P.MODEL NOT IN (SELECT MODEL FROM LAPTOP)

SELECT DISTINCT P.MAKER FROM PRODUCT P
JOIN LAPTOP L ON L.model = P.model
WHERE P.MAKER IN(SELECT S.MAKER FROM PRODUCT S JOIN PRINTER PR ON PR.model=S.model);

SELECT DISTINCT P1.HD FROM LAPTOP P1 
JOIN LAPTOP P2 ON P1.hd=P2.hd
WHERE P1.model!=P2.model

SELECT P.MODEL FROM PRODUCT P
RIGHT JOIN PC P1 ON P.model=P1.model
WHERE P.maker NOT IN (SELECT MAKER FROM PRODUCT WHERE TYPE = 'PC')