SELECT * FROM SHIPS S
JOIN CLASSES C ON C.CLASS=S.CLASS

SELECT * FROM SHIPS S
RIGHT JOIN CLASSES C ON C.CLASS=S.CLASS
WHERE C.CLASS IN (SELECT NAME FROM SHIPS)
OR S.CLASS IN (SELECT CLASS FROM CLASSES)

SELECT C.COUNTRY,S.NAME 
FROM SHIPS S
JOIN CLASSES C ON S.CLASS=C.CLASS
WHERE S.NAME NOT IN (SELECT SHIP FROM OUTCOMES)
order by 1,2;

SELECT S.NAME AS 'Ship Name' 
FROM SHIPS S
JOIN CLASSES C ON C.CLASS=S.CLASS
WHERE C.NUMGUNS>=7
AND S.LAUNCHED=1916;

SELECT O.SHIP,O.BATTLE,B.DATE 
FROM OUTCOMES O
JOIN BATTLES B ON B.NAME=O.BATTLE
WHERE O.RESULT = 'sunk'
order by 2;

SELECT S.NAME,C.DISPLACEMENT,S.LAUNCHED 
FROM SHIPS S
JOIN CLASSES C ON C.CLASS=S.CLASS
WHERE S.NAME=C.CLASS

SELECT C.CLASS,C.TYPE,C.COUNTRY,C.NUMGUNS,C.BORE,C.DISPLACEMENT 
FROM CLASSES C
LEFT JOIN SHIPS S ON C.CLASS=S.CLASS
WHERE C.CLASS NOT IN (SELECT CLASS FROM SHIPS)

SELECT S.NAME,C.DISPLACEMENT,C.NUMGUNS,O.RESULT FROM SHIPS S
JOIN OUTCOMES O ON O.SHIP = S.NAME
JOIN CLASSES C ON C.CLASS = S.CLASS
WHERE BATTLE = 'North Atlantic';