/* #1 */
SELECT AVG(SPEED) as AVGSpeed 
FROM PC
/* #2 */
SELECT MAKER,AVG(SCREEN) AS AVGScreen 
FROM PRODUCT P
JOIN LAPTOP L ON L.model=P.model
GROUP BY MAKER
/* #3 */
SELECT AVG(SPEED) 
FROM LAPTOP
WHERE PRICE>1000
/* #4 */
SELECT MAKER,ROUND(AVG(PRICE),2) AS AVGPRICE 
FROM PC B
JOIN PRODUCT P ON P.model=B.MODEL
WHERE P.maker='A'
GROUP BY MAKER
/* #5 */
SELECT MAKER,AVG(S.PRICE) AS AVGPRICE
FROM (SELECT PRICE,MODEL
		FROM LAPTOP 
		UNION ALL
		SELECT PRICE,MODEL
		FROM PC)S
JOIN PRODUCT P ON P.model=S.model
WHERE P.maker='B'
GROUP BY MAKER
/* #6 */
SELECT SPEED,AVG(PRICE) AS AVGPRICE
FROM PC
GROUP BY SPEED
/* #7 */
SELECT MAKER,COUNT(DISTINCT CODE) AS 'Num OF PC' 
FROM PC P
JOIN PRODUCT PR ON P.model=PR.model
GROUP BY MAKER
HAVING COUNT(DISTINCT CODE)>=3
/* #8 */
SELECT MAKER,PRICE AS MAXPRICE
FROM PC P
JOIN PRODUCT PR ON P.model=PR.model
WHERE PRICE = (SELECT MAX(PRICE) FROM PC)
/* #9 */
SELECT SPEED,PRICE AS AVGPRICE
FROM PC P
WHERE PRICE =(SELECT AVG(PRICE) FROM PC WHERE SPEED>=800)
/* #10 */
SELECT MAKER,AVG(HD) AS AGHD 
FROM PC P
JOIN PRODUCT PR ON P.model=PR.model
GROUP BY MAKER
HAVING PR.maker IN (SELECT PR2.MAKER FROM PRODUCT PR2 JOIN PRINTER PN ON PR2.model=PN.MODEL)

