SELECT COUNT(DISTINCT CLASS) AS CLAss FROM CLASSES
WHERE TYPE ='bb'

SELECT CLASS,AVG(NUMGUNS) AS AVGGUNS FROM CLASSES
WHERE TYPE = 'bb'
GROUP BY CLASS

SELECT AVG(NUMGUNS) AS AVGGUNS FROM CLASSES
WHERE TYPE = 'bb'

SELECT C.CLASS,MIN(LAUNCHED) AS FIRST_YEAR,MAX(LAUNCHED) AS LAST_YEAR FROM CLASSES C
JOIN SHIPS S ON C.CLASS = S.CLASS
GROUP BY C.CLASS

SELECT CLASS,COUNT(RESULT) AS NUMBER_OF_SUNK_SHIPS FROM OUTCOMES O
JOIN SHIPS S ON O.SHIP=S.NAME
WHERE RESULT='sunk'
GROUP BY CLASS

SELECT CLASS,COUNT(RESULT) AS NUMBER_OF_SUNK_SHIPS FROM OUTCOMES O
JOIN SHIPS S ON O.SHIP=S.NAME
WHERE RESULT='sunk'
GROUP BY CLASS
HAVING (SELECT COUNT(S1.NAME) FROM SHIPS S1 WHERE S1.CLASS=CLASS)>2;

SELECT COUNTRY,ROUND(AVG(BORE),2) AS AVG_BORE FROM CLASSES C
JOIN SHIPS S ON S.CLASS = C.CLASS
GROUP BY COUNTRY

