SELECT M.TITLE,M.YEAR,M.LENGTH FROM MOVIE M
WHERE M.LENGTH > 120 
OR M.LENGTH IS NULL
AND YEAR<2000

SELECT NAME,GENDER FROM MOVIESTAR
WHERE NAME LIKE 'J%'
AND BIRTHDATE >'1948-12-31'
ORDER BY NAME DESC;

SELECT MV.STUDIONAME,COUNT(DISTINCT SI.STARNAME) AS NUMBER_OF_STARS
FROM MOVIE MV
JOIN STARSIN SI ON MV.TITLE = SI.MOVIETITLE
GROUP BY MV.STUDIONAME;

SELECT MS.NAME,COUNT(SI.MOVIETITLE) AS MOVIECOUNT
FROM MOVIESTAR MS
JOIN STARSIN SI ON MS.NAME=SI.STARNAME
GROUP BY MS.NAME;

SELECT M.STUDIONAME,M.TITLE,M.YEAR 
FROM MOVIE M
WHERE M.YEAR >= ALL(SELECT M2.YEAR FROM MOVIE M2 WHERE M2.STUDIONAME=M.STUDIONAME);

SELECT MS.NAME FROM MOVIESTAR MS
WHERE YEAR(MS.BIRTHDATE) >= ALL(SELECT YEAR(MS2.BIRTHDATE) FROM MOVIESTAR MS2 WHERE MS2.GENDER='M')
AND MS.GENDER='M';

SELECT M.STUDIONAME,SI.STARNAME,COUNT(SI.MOVIETITLE) AS AMOUNTOFMOVIESDONE FROM MOVIE M
JOIN STARSIN SI ON SI.MOVIETITLE=M.TITLE
AND SI.MOVIEYEAR=M.YEAR
JOIN MOVIESTAR MS ON MS.NAME = SI.STARNAME
WHERE MS.GENDER = 'M'
GROUP BY  M.STUDIONAME,SI.STARNAME
HAVING COUNT(SI.MOVIETITLE) >=ALL(SELECT COUNT(SI2.MOVIETITLE) FROM STARSIN SI2 
									JOIN MOVIE M2 ON M2.YEAR=SI2.MOVIEYEAR 
									AND M2.TITLE = SI2.MOVIETITLE GROUP BY M2.STUDIONAME,SI2.STARNAME);

SELECT MV.YEAR,MV.TITLE,COUNT(SI.STARNAME) AS NUMBEROFACTORS
FROM MOVIE MV 
JOIN STARSIN SI ON SI.MOVIETITLE = MV.TITLE
AND SI.MOVIEYEAR = MV.YEAR
GROUP BY MV.YEAR,MV.TITLE
HAVING COUNT(SI.STARNAME)>2;
