SELECT L1.MODEL,L1.CODE,L1.SCREEN FROM LAPTOP L1
JOIN LAPTOP L2 ON L1.model=L2.model
WHERE L1.screen=15
AND L2.screen=11
OR L1.screen=11
AND L2.screen=15

SELECT DISTINCT P.MODEL FROM PC P
JOIN PRODUCT PR ON PR.model=P.model 
WHERE P.price<(SELECT MIN(L.PRICE) FROM LAPTOP L JOIN PRODUCT PR1 ON L.model=PR1.model WHERE PR1.maker=PR.MAKER)

SELECT DISTINCT P.MODEL,AVG(P.PRICE) AS AVG_PRICE FROM PC P
JOIN PRODUCT PR ON PR.MODEL = P.MODEL
GROUP BY P.MODEL,PR.maker
HAVING AVG(P.PRICE)<(SELECT MIN(L.PRICE) FROM LAPTOP L JOIN PRODUCT PR1 ON L.model=PR1.model WHERE PR1.maker=PR.MAKER);

SELECT P.CODE,PR.MAKER,COUNT(P1.CODE) FROM PC P
JOIN PRODUCT PR ON P.model=PR.model
JOIN PC P1 ON P.price<=P1.price
WHERE P1.model=PR.model
GROUP BY P.CODE,PR.MAKER


