SELECT DISTINCT SHIP FROM OUTCOMES
WHERE SHIP LIKE 'C%' 
OR SHIP LIKE 'K%';

SELECT DISTINCT S.NAME,C.COUNTRY FROM SHIPS S 
JOIN CLASSES C ON C.CLASS = S.CLASS
JOIN OUTCOMES O ON S.NAME = O.SHIP 
AND RESULT != 'SUNK' 
OR S.NAME NOT IN (SELECT SHIP FROM OUTCOMES);

SELECT C.COUNTRY,COUNT(RESULT) as 'Sunken Ships' FROM SHIPS S
RIGHT JOIN CLASSES C ON S.CLASS =C.CLASS
LEFT JOIN OUTCOMES O ON S.NAME = O.SHIP 
WHERE O.RESULT ='sunk'
OR O.RESULT IS NULL
GROUP BY C.COUNTRY

SELECT BATTLE FROM OUTCOMES 
GROUP BY BATTLE
HAVING COUNT(SHIP)>(SELECT COUNT(SHIP) FROM OUTCOMES WHERE BATTLE = 'Guadalcanal')

SELECT BATTLE FROM OUTCOMES 
GROUP BY BATTLE
HAVING COUNT(SHIP)>(SELECT COUNT(SHIP) FROM OUTCOMES WHERE BATTLE = 'Surigao Strait')

SELECT S.NAME,C.DISPLACEMENT,C.NUMGUNS FROM SHIPS S
JOIN CLASSES C ON S.CLASS = C.CLASS
WHERE C.DISPLACEMENT <= ALL(SELECT C1.DISPLACEMENT FROM CLASSES C1 JOIN SHIPS S1 ON C1.CLASS = S1.CLASS)
AND C.NUMGUNS >=ALL(SELECT C2.NUMGUNS FROM CLASSES C2 JOIN SHIPS S2 ON C2.CLASS = S2.CLASS 
					WHERE C2.DISPLACEMENT<=ALL(SELECT C1.DISPLACEMENT FROM CLASSES C1 JOIN SHIPS S1 ON C1.CLASS = S1.CLASS))

SELECT COUNT(O1.SHIP) AS RECOVEREDSHIPS FROM OUTCOMES O1
JOIN OUTCOMES O2 ON  O1.SHIP=O2.SHIP
WHERE O1.RESULT = 'damaged'
AND O2.RESULT = 'ok';

SELECT O1.SHIP AS RECOVEREDSHIPS FROM OUTCOMES O1
JOIN OUTCOMES O2 ON O1.SHIP=O2.SHIP
JOIN BATTLES B1 ON B1.NAME = O1.BATTLE
JOIN BATTLES B2 ON B2.NAME = O2.BATTLE
WHERE O1.RESULT = 'damaged'
AND O2.RESULT = 'ok'
AND B1.DATE < B2.DATE
AND (SELECT COUNT(OUT1.SHIP) FROM OUTCOMES OUT1 WHERE OUT1.BATTLE = B1.NAME) < (SELECT COUNT(OUT2.SHIP) FROM OUTCOMES OUT2 WHERE OUT2.BATTLE = B2.NAME);
