SELECT me.NAME FROM MOVIEEXEC me ,(SELECT NAME FROM MOVIESTAR WHERE GENDER ='F')ms
WHERE me.NAME=ms.NAME 
AND me.NETWORTH > 10000000

SELECT DISTINCT ms.NAME FROM MOVIESTAR ms
WHERE ms.NAME != ANY(SELECT NAME FROM MOVIEEXEC);

SELECT DISTINCT m.TITLE FROM MOVIE m
WHERE m.LENGTH > (SELECT LENGTH FROM MOVIE WHERE TITLE = 'Star Wars');

SELECT DISTINCT F.TITLE, T.NAME FROM MOVIE F,(SELECT CERT#,NAME FROM MOVIEEXEC WHERE NETWORTH > (SELECT NETWORTH FROM MOVIEEXEC WHERE NAME = 'Merv Griffin') )T
WHERE F.PRODUCERC#=T.CERT#;
