/* EX1 */
SELECT DISTINCT P.MAKER FROM PRODUCT P,(SELECT MODEL FROM PC WHERE SPEED > 500)P2
WHERE P.model=P2.model
/* THE ONE BELOW IS BETTER */
SELECT MAKER FROM PRODUCT 
WHERE MODEL IN (SELECT MODEL FROM PC WHERE SPEED > 500)
/* EX2 */
SELECT L.CODE,L.MODEL,L.PRICE FROM PRINTER L
WHERE L.PRICE >= ALL(SELECT PRICE FROM PRINTER);
/* EX3 */
SELECT * FROM LAPTOP 
WHERE SPEED < ALL(SELECT SPEED FROM PC)
/* EX4 */

