/* EX1 */
SELECT DISTINCT P.MAKER FROM PRODUCT P,(SELECT MODEL FROM PC WHERE SPEED > 500)P2
WHERE P.model=P2.model
/* THE ONE BELOW IS BETTER */
SELECT MAKER FROM PRODUCT 
WHERE MODEL IN (SELECT MODEL FROM PC WHERE SPEED > 500)
/* EX2 */
SELECT L.CODE,L.MODEL,L.PRICE FROM PRINTER L
WHERE L.PRICE >= ALL(SELECT PRICE FROM PRINTER);
/* EX3 */
SELECT * FROM LAPTOP 
WHERE SPEED < ALL(SELECT SPEED FROM PC)
/* EX4 */
SELECT MODEL,PRICE FROM (SELECT MODEL,PRICE FROM PRINTER UNION SELECT MODEL,PRICE FROM LAPTOP UNION SELECT MODEL,PRICE FROM PC) S
WHERE Price >= ALL(SELECT PRICE FROM PRINTER UNION SELECT PRICE FROM LAPTOP UNION SELECT PRICE FROM PC);
/* EX5 */
SELECT MAKER FROM PRODUCT
WHERE PRODUCT.MODEL = (SELECT MODEL FROM PRINTER WHERE PRICE<=ALL(SELECT PRICE FROM PRINTER WHERE COLOR='Y') AND COLOR = 'Y')
/* EX6 */
SELECT DISTINCT MAKER FROM PRODUCT , (SELECT MODEL,RAM,SPEED FROM PC WHERE RAM<=ALL(SELECT RAM FROM PC)) P
WHERE PRODUCT.model = P.model
AND P.speed>=ALL(SELECT SPEED FROM PC WHERE RAM<=ALL(SELECT RAM FROM PC))

 